# Generated by Django 4.1.5 on 2023-01-08 12:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import satta.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order', models.IntegerField(unique=True)),
                ('time_of_day', models.TimeField(auto_now=True)),
                ('result_delta', satta.models.IntegerRangeField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=255)),
                ('mobile_number', models.IntegerField()),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('winning_number', models.PositiveIntegerField()),
                ('winning_number_adjusted', models.BooleanField()),
                ('adjusted_winning_number', models.IntegerField(null=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satta.slot')),
                ('winner_declared_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='satta.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder', satta.models.IntegerRangeField()),
                ('bid_value', satta.models.IntegerRangeField()),
                ('bid_amount', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satta.slot')),
            ],
        ),
    ]
