# Generated by Django 4.1.5 on 2023-01-08 13:21

from django.db import migrations
import satta.models


class Migration(migrations.Migration):

    dependencies = [
        ('satta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_value',
            new_name='bid_number',
        ),
        migrations.AlterField(
            model_name='slot',
            name='time_of_day',
            field=satta.models.IntegerRangeField(),
        ),
    ]
